apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskmanager-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OletiSatishKumar/TaskManager_MERN_Infra_2.git'
    targetRevision: HEAD
    path: dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
